### ISSUE TITLE
Ошибка в конспекте по алгебре

### ISSUE THREAD

**Issue by das747** [khbminus/HSE-summaries#1]
https://github.com/khbminus/HSE-summaries/blob/b299ff016e6b97a7feb0bd4808be98b9b145018e/src/term1-algebra/03-rings.tex#L115
Думаю правая часть должна вот так выглядеть:
`\underbrace{(a-b)}_{\vdots n} - \underbrace{(b+d)}_{\vdots n} \vdots n`

кроме того, возможно такой символ делимости лучше выглядит:
`\newcommand{\divisible}{\mathop{\raisebox{-1pt}{\vdots}}}`

![image](https://user-images.githubusercontent.com/40293014/134810107-f1c1bb71-764f-45c5-afa7-721117864a6e.png)

**Comment by hsevm** [comment]
Ой, ты две одинаковые картинки скинул

Не знаю зачем, но пофикшено. btw про значок согласен

**Comment by das747** [comment]
Блин, я дурачок,  пока искал как код вставить забыл исправить

Думаю правая часть должна вот так выглядеть:
`\underbrace{(a-b)}_{\vdots n} + \underbrace{(с - d)}_{\vdots n} \vdots n`

**Comment by das747** [comment]
А, забей, я ещё раз дурачок, по ссылке из первого коммента старый коммит

**Comment by khbminus** [comment]
Неожиданно, но символ делимости стал приятнее (спустя месяц!)
