### ISSUE TITLE
Ошибки в конспекте по матанализу

### ISSUE THREAD

**Issue by das747** [khbminus/HSE-summaries#2]
непустое и **ограничено сверху**
https://github.com/khbminus/HSE-summaries/blob/838a4c8d1fda77b0ca3d16e53ab7230b59c59f51/src/term1-anal/02-inf.tex#L12 

непустое и **ограничено снизу** 
https://github.com/khbminus/HSE-summaries/blob/838a4c8d1fda77b0ca3d16e53ab7230b59c59f51/src/term1-anal/02-inf.tex#L30

**Comment by hsevm** [comment]
Fixed
