### ISSUE TITLE
Конспект по матлогу 1 лекция

### ISSUE THREAD

**Issue by das747** [khbminus/HSE-summaries#41]
там явно должны быть не переносы
https://github.com/khbminus/HSE-summaries/blob/4f967a2674f975ab93f40f9d9040b11a9a992825/src/term2-logic/01-sets.tex#L69

тут не отрисовался setminus
https://github.com/khbminus/HSE-summaries/blob/4f967a2674f975ab93f40f9d9040b11a9a992825/src/term2-logic/01-sets.tex#L120
https://github.com/khbminus/HSE-summaries/blob/4f967a2674f975ab93f40f9d9040b11a9a992825/src/term2-logic/01-sets.tex#L122

0 вместо -
https://github.com/khbminus/HSE-summaries/blob/4f967a2674f975ab93f40f9d9040b11a9a992825/src/term2-logic/01-sets.tex#L144

**Comment by khbminus** [comment]
Все, кроме 0 исправлено

**Comment by MarkTheHopeful** [comment]
Всё, теперь всё исправлено
